#!/bin/bash

function start()
{
  cd /home/work/dea_ng/bin 
  nohup ruby dea ../config/dea.yml > /dev/null 2>&1 &
  sleep 1
}

function stop()
{
  ps -ef | grep 'ruby de[a]' | awk '{print $2}' | xargs kill
  while ps -ef | grep 'ruby de[a]' ;do sleep 1;done
}

function restart()
{
  stop
  start
}

case ${1:-"other"} in
  start) start ;;
  stop) stop ;;
  restart) restart ;;
  *) echo "Usage: $0 start|stop|restart" ;;
esac
